version: "3"

services:
  mosquitto:
    image: eclipse-mosquitto
    ports:
      - 1234:1234
      - 1234:1234
    volumes:
      - mosquitto-data:/mosquitto/data
      - mosquitto-logs:/mosquitto/logs
      - ./mosquitto-conf:/mosquitto/config
    restart: unless-stopped

volumes:
  mosquitto-data:
  mosquitto-logs:
  mosquitto-conf:
